const AGREGAR_PRODUCTO = 'AGREGAR_PRODUCTO';
const AGREGAR_PRODUCTO_EXITO = 'AGREGAR_PRODUCTO_EXITO';
const AGREGAR_PRODUCTO_ERROR = 'AGREGAR_PRODUCTO_ERROR';


module.exports  = {
    AGREGAR_PRODUCTO,
    AGREGAR_PRODUCTO_EXITO,
    AGREGAR_PRODUCTO_ERROR
}