const AGREGAR_PRODUCTO = 'AGREGAR_PRODUCTO';
const AGREGAR_PRODUCTO_EXITO = 'AGREGAR_PRODUCTO_EXITO';
const AGREGAR_PRODUCTO_ERROR = 'AGREGAR_PRODUCTO_ERROR';

const DESCARGAR_PRODUCTOS = 'DESCARGAR_PRODUCTOS';
const DESCARGAR_PRODUCTOS_EXITO = 'DESCARGAR_PRODUCTOS_EXITO';
const DESCARGAR_PRODUCTOS_ERROR = 'DESCARGAR_PRODUCTOS_ERROR';

const ELIMINAR_PRODUCTO = 'ELIMINAR_PRODUCTO';
const ELIMINAR_PRODUCTO_EXITO = 'ELIMINAR_PRODUCTO_EXITO';
const ELIMINAR_PRODUCTO_ERROR = 'ELIMINAR_PRODUCTO_ERROR';

const OBTENER_PRODUCTO_ACTUALIZAR = 'OBTENER_PRODUCTO_ACTUALIZAR';
const INICIAR_EDICION_PRODUCTO = 'INICIAR_EDICION_PRODUCTO';
const ACTUALIZAR_PRODUCTO_EXITO = 'ACTUALIZAR_PRODUCTO_EXITO';
const ACTUALIZAR_PRODUCTO_ERROR = 'ACTUALIZAR_PRODUCTO_ERROR';

const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

module.exports  = {
    AGREGAR_PRODUCTO,
    AGREGAR_PRODUCTO_EXITO,
    AGREGAR_PRODUCTO_ERROR,
    DESCARGAR_PRODUCTOS,
    DESCARGAR_PRODUCTOS_EXITO,
    DESCARGAR_PRODUCTOS_ERROR,
    ELIMINAR_PRODUCTO,
    ELIMINAR_PRODUCTO_EXITO,
    ELIMINAR_PRODUCTO_ERROR,
    OBTENER_PRODUCTO_ACTUALIZAR,
    ACTUALIZAR_PRODUCTO_EXITO,
    ACTUALIZAR_PRODUCTO_ERROR,
    INICIAR_EDICION_PRODUCTO,
    MOSTRAR_ALERTA,
    OCULTAR_ALERTA
}